# Generated by Django 4.0.1 on 2022-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mailing',
            field=models.BooleanField(default=False),
        ),
    ]
