# Generated by Django 4.0.1 on 2022-07-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_checkout_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='checkout_session_id',
            new_name='customer_id',
        ),
    ]
