# Generated by Django 4.0.1 on 2022-07-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='user',
        ),
    ]
