# Generated by Django 4.0.1 on 2022-07-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
